"""empty message

Revision ID: 33c0cdb86774
Revises: 
Create Date: 2024-06-22 15:47:47.387080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c0cdb86774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_mqa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('avaliado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_mqa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_mqa_avaliado_em'), ['avaliado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_mqa_nome_arquivo'), ['nome_arquivo'], unique=True)
        batch_op.create_index(batch_op.f('ix_score_mqa_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_mqa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_mqa_score'))
        batch_op.drop_index(batch_op.f('ix_score_mqa_nome_arquivo'))
        batch_op.drop_index(batch_op.f('ix_score_mqa_avaliado_em'))

    op.drop_table('score_mqa')
    # ### end Alembic commands ###
